# Generated by Django 3.0.4 on 2020-10-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_work_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(default='123', max_length=250),
        ),
    ]
